#!/bin/bash
if [[ "$1" != "" ]]; then
    calc="$1"
else
    calc=flint
fi

START=$(date +%s.%N)
mpirun -np 5 bin/FIRE7_MPI --delete_tables --calc ${calc} $2 --reconstruct -T 8_8_14 -P 3 -I 80_90_100 -E -c examples/doublebox3N
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "Total time of the script: $DIFF"
