#!/bin/bash
START=$(date +%s.%N)
for d in {1..26}
do
    for p in {1..3}
    do
        bin/FIRE7p "$@" -v 7^"$d"_"$p" -c examples/box --large_variables --quiet
    done
done
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "Total time of the script: $DIFF"
