#!/bin/bash
if [[ "$1" != "" ]]; then
    calc="$1"
else
    calc=flint
fi

START=$(date +%s.%N)
mpirun -np 5 bin/FIRE7_MPI --delete_tables --calc ${calc} -Z $2 --reconstruct -P 3 -I 80_90_100 -E -S -c examples/doublebox3N
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "Total time of the script: $DIFF"
