#!/bin/bash
START=$(date +%s.%N)
for d in {100..112}
do
    for s in {57..62}
    do
        for p in {1..3}
        do
            bin/FIRE7p -v "$d"_"$s"_3_"$p" -c examples/doublebox --quiet
        done
    done
done
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "Total time of the script: $DIFF"
