sonar.projectKey=feynmanintegrals_fire_AZagKGLmvyeU6XldrwSA
sonar.qualitygate.wait=true
sonar.sources=.
sonar.projectBaseDir=FIRE7
sonar.exclusions=/usr/**,/extra/**,/tmp/**,documentation/**
sonar.cpd.exclusions="**/*.*"
sonar.coverage.exclusions="**/*.*"
