#!/bin/bash
START=$(date +%s.%N)
for d in {100..120}
do
    for s in {100..110}
    do
        for p in {1..3}
        do
            echo temp/doublebox-$d-$s-$p.tables
            if [ ! -f temp/doublebox-$d-$s-$p.tables ]; then bin/FIRE6p $d-$s-$p examples/doublebox2; fi;
        done
    done
done
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "Total time of the script: $DIFF"
