#!/bin/bash
START=$(date +%s.%N)
for d in {100..125}
do
    for p in {1..4}
    do
        bin/FIRE6p -variables $d-$p -c examples/box
    done
done
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "Total time of the script: $DIFF"
